version: '3'
services:
  backend:
    networks:
        - main
    build:
      context: .
      dockerfile: ./src/API/CoreApi/Dockerfile
    ports:
      - "5000:8080"
      - "5001:80" 
    depends_on:
      - database
    environment:
        ConnectionStrings__Database: "host=database;port=5432;database=acrhitrekdb;username=admin;password=admin"

  frontend:
    build:
      context: ./src/ClientApp
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
        - backend

  database:
    image: "postgis/postgis:latest"
    networks:
        - main
    ports:
    - "5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: architekdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin


volumes:
    postgres_data:

networks:
    main:
        driver: bridge