version: '3.1'

services:
	coreapi:
		image: coreapi
		build:
			context: .
			dockerfile: ./src/API/CoreApi/Dockerfile
		ports:
			- "90:80"
		depends_on:
			- coredb
		environment:
			- ConnectionStrings__DefaultConnection=Host=maindb;Port=5432;
		networks:
			- corenetwork

	coredb:
		image: postgres:latest
		ports:
			- "5432:5432"
		environment:
			POSTGRES_DB: coredb
			POSTGRES_USER: sdf
			POSTGRES_PASSWORD: sdf
		volumes:
		    - coredb_data:/var/lib/postgresql/data
		networks:
			- corenetwork

	
	angular:
		image: angular
		ports:
			- "4200:4200"
		environment:
			API_URL = "H"
		    

secrets:
    coredb:
	

volumes:
	coredb_data:
	
		
networks:
	corenetwork:
		driver: bridge